### PR TITLE
Support pulling from registry v2

### PR DESCRIPTION
**Pull request by abresas**
This change is [Reviewable](https://reviewable.io/reviews/resin-io/docker-progress/9)

### CODE REVIEW

**Comment by abresas** [comment]
Please review https://github.com/resin-io/docker-progress/pull/8 first.

**Comment by abresas** [comment]
Have tested it locally against 1.9.1 and 1.10.1

**Comment by Page-** [comment]
test this please

**Comment by Page-** [comment]
`index.js` shouldn't be included in the PR, I'm waiting to review the rest on #8 as you said

**Pull request merged**
